import React from 'react';
import NavBarComponent from './Navbar';

const Home = () => {
    return (
        <div>
            <h1 class="text-center">EPIC LOGO</h1>
            <NavBarComponent />
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent erat ex, sollicitudin in quam sodales, gravida pharetra tortor. Etiam ligula lorem, lobortis non augue vel, volutpat elementum odio. Fusce dolor libero, aliquet vel tempus vitae, commodo eget neque. Etiam iaculis, massa eget commodo pulvinar, lorem tellus rutrum purus, porta porta leo lacus vitae orci. Quisque vel magna nec ipsum tempor scelerisque. Phasellus placerat nibh ac metus ornare porttitor. Suspendisse potenti. In non ipsum ac ligula viverra interdum nec vel quam. Duis et pulvinar leo. Ut sed risus turpis. Cras ultrices finibus dolor sed lacinia. Quisque a luctus magna, posuere tempor velit. Vivamus ut neque erat. Phasellus eu orci et mi euismod viverra vitae eget ligula. Sed mi risus, molestie eget imperdiet eget, eleifend eu sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

                Nulla aliquam diam eu blandit hendrerit. Cras laoreet maximus enim a faucibus. Phasellus sit amet hendrerit justo. Proin egestas elementum leo ultricies ornare. Morbi vulputate, odio eu efficitur lacinia, dui nisi finibus elit, sed vestibulum magna nunc a ante. Donec dolor ligula, dapibus consequat sapien ac, tempus hendrerit arcu. Quisque auctor sed metus quis malesuada. Nam nisi urna, fringilla ut mollis non, porta nec purus. Mauris id venenatis lacus. Nunc ut quam placerat, ultrices mi quis, feugiat massa. Donec non magna enim. Pellentesque id viverra orci. Etiam enim turpis, imperdiet eu nunc id, pharetra sodales lectus.

                Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ac interdum leo. Donec fringilla dapibus massa ut finibus. Vestibulum tortor ex, scelerisque ac turpis ut, sodales aliquet nunc. Nullam ultricies posuere dapibus. In gravida ante at tincidunt facilisis. Sed eget ipsum eros. Curabitur bibendum ultricies scelerisque. Integer pellentesque maximus neque eget tempus. Aenean vitae nibh vitae est ullamcorper lacinia sed a felis.

                Nam euismod leo et augue maximus, non tempor nibh efficitur. Vivamus laoreet lectus id odio facilisis, venenatis rhoncus diam tincidunt. Donec luctus eros tristique felis vulputate, quis faucibus diam molestie. Nunc leo turpis, hendrerit nec tortor ut, molestie posuere sem. Morbi nec sodales lectus. Sed tincidunt, est vel facilisis rutrum, nibh tellus vulputate purus, eu aliquam dui erat eget diam. Maecenas fringilla arcu in nisi placerat fringilla. Fusce vel magna quis est hendrerit fringilla. Nullam iaculis consequat varius.

                Nullam ullamcorper, augue in efficitur tincidunt, neque arcu faucibus nulla, sed pulvinar dolor lectus eget ipsum. Proin laoreet mauris quam, ut dictum justo pretium id. Mauris ultrices felis sed aliquam sodales. Integer ac arcu nulla. Aliquam placerat lacus molestie, molestie quam mollis, vestibulum nunc. Fusce neque enim, cursus in consectetur nec, tempus laoreet velit. Vestibulum vulputate vulputate purus, at pulvinar diam vestibulum nec. Fusce at aliquam odio. Praesent consectetur commodo porta. Nunc sodales eros a pellentesque rhoncus. Nulla facilisi. Nullam dolor dolor, aliquam et risus eget, tincidunt maximus odio. Integer tincidunt tortor dolor, vel posuere ipsum ullamcorper eget.

                Nulla ante diam, facilisis ut scelerisque a, lacinia ut ipsum. Phasellus dignissim, libero sed vestibulum dictum, risus metus vestibulum eros, at elementum erat metus eu nibh. In hac habitasse platea dictumst. Pellentesque ac viverra lorem, lobortis viverra lacus. Proin accumsan mollis enim, sit amet auctor nunc euismod at. Sed fermentum eu nunc id efficitur. Praesent consequat purus sem, id dictum nulla vulputate id.

                Nullam eu lorem felis. Vivamus vel venenatis mi, vitae dignissim quam. Pellentesque sit amet enim vulputate, egestas dui id, congue ante. Nunc non nibh porta, dapibus enim ut, rutrum enim. Maecenas mollis mollis lectus, sit amet dignissim mi feugiat a. In hac habitasse platea dictumst. Nam aliquet magna non molestie fringilla. Aenean congue turpis lectus, vitae fermentum neque interdum eu. Pellentesque pharetra tempus lacinia.

                Donec consequat convallis nibh. Quisque ultricies eget nunc ac sollicitudin. Donec et lorem diam. In tristique felis vitae augue aliquet, at interdum risus luctus. Phasellus quis massa vitae metus aliquet congue non in quam. Duis tristique urna eu nisi pharetra tempor. Etiam orci tortor, commodo in pellentesque sed, dignissim at quam. Etiam non ante eget nibh bibendum ultrices at vehicula purus. In pretium sem ut neque mattis hendrerit. Integer sollicitudin congue eros a ornare. Maecenas egestas laoreet nisi quis euismod. Suspendisse id lorem lacus. Mauris sit amet mauris turpis. Etiam nisl diam, placerat suscipit dignissim vitae, lobortis non erat. Morbi sed est vel magna iaculis dictum ac vitae ligula.

                Nullam in nibh rhoncus, venenatis lacus a, suscipit purus. Praesent orci nisi, cursus a ultricies non, tincidunt non dui. Ut diam lacus, commodo eu fringilla in, volutpat at lectus. Cras ut facilisis ligula. Donec vitae odio eget ipsum varius efficitur sit amet eu turpis. Nam pellentesque elementum dui. Etiam risus mi, malesuada in tincidunt sed, laoreet eget tortor. Nulla eu nunc volutpat, dignissim nunc a, convallis augue. Pellentesque interdum nibh non suscipit sagittis. Donec sit amet condimentum est, id elementum tortor.

                Pellentesque turpis dui, congue in purus sit amet, suscipit dapibus magna. Praesent vel lorem sed purus tincidunt volutpat. Quisque sit amet ex id lacus ornare vulputate. Ut a dolor ac ex vestibulum congue. Proin laoreet, sem semper malesuada ultrices, justo dolor ornare nisi, ut ultrices mauris turpis a orci. Aliquam justo neque, egestas imperdiet magna ut, pulvinar fringilla est. Suspendisse euismod lectus nec placerat dictum. Aliquam ultrices arcu et quam ultrices laoreet. Etiam imperdiet, ex eu venenatis dignissim, sapien ligula convallis odio, non pellentesque eros ipsum non felis. Vestibulum ultricies et lectus ut lobortis. Suspendisse mattis ligula nisl, non hendrerit tortor facilisis ut. Curabitur luctus justo eget lacinia iaculis. Aliquam vel velit eget nisi volutpat ultrices a eget ligula. Suspendisse tincidunt, risus pulvinar blandit tincidunt, mauris turpis consequat neque, ut auctor dolor leo ac nibh. Praesent pulvinar est non velit tincidunt, non pharetra enim fringilla.

                Quisque nisi ligula, commodo quis pellentesque sed, auctor ac enim. Phasellus pellentesque, felis ut consectetur sodales, sapien mauris suscipit mauris, in elementum elit leo at orci. Aenean in mauris odio. Proin et nulla sed lorem porttitor lacinia sed a felis. Cras pulvinar at massa efficitur bibendum. Praesent ullamcorper tortor non risus tincidunt semper. In interdum ullamcorper felis, id pellentesque mi scelerisque lobortis. Suspendisse porttitor accumsan scelerisque. Ut mollis rhoncus enim sit amet tempor. Phasellus suscipit semper neque eget varius. Quisque id odio sit amet urna malesuada sollicitudin vel sit amet ex. Vestibulum purus odio, porttitor et varius sed, iaculis in tellus. Maecenas elementum in sapien ac suscipit.

                Mauris ut est non felis eleifend rhoncus. Nulla pulvinar accumsan felis, quis tristique justo commodo id. Nunc ac blandit nibh. Nullam imperdiet, velit vel suscipit egestas, nunc ipsum rutrum orci, a vehicula sem lacus placerat orci. Proin enim metus, porta blandit nunc id, ullamcorper faucibus ligula. Nullam vel suscipit nunc. Sed eu sapien a arcu pharetra rhoncus. Vivamus ullamcorper velit et imperdiet molestie. Maecenas facilisis, lorem at cursus interdum, ipsum arcu egestas augue, efficitur vehicula metus felis eleifend lectus. Suspendisse eu neque efficitur, fermentum purus eu, pharetra quam. Vivamus elementum sollicitudin ultricies.

                Proin eget elit nisl. Donec tristique lacinia sem eu posuere. Suspendisse potenti. Pellentesque egestas tellus nec dolor ultrices, vitae semper eros placerat. Quisque vehicula aliquet felis non rutrum. Nunc ac augue turpis. Morbi molestie arcu nibh, sed commodo orci placerat id. Nulla ac eros nunc. Etiam faucibus ipsum dolor, a dignissim arcu facilisis non. Sed blandit cursus erat, sed lobortis ante pretium non. Mauris eleifend id enim in condimentum. Duis sed purus eget dui tincidunt rutrum sit amet ac quam. Suspendisse sollicitudin accumsan velit, in efficitur diam volutpat eu. Donec sagittis nisl libero, sit amet imperdiet neque rhoncus at.

                Praesent convallis neque ex. Nunc sed magna at tellus volutpat egestas. Vivamus laoreet ullamcorper magna sed scelerisque. Sed a aliquam lectus, id tempor nisl. Suspendisse porta felis arcu, ac tristique nulla aliquet sed. Fusce tincidunt at nulla non ultricies. Donec vitae purus non dolor ullamcorper lobortis id a magna. Duis nunc sapien, condimentum ut porttitor sit amet, condimentum quis turpis. Proin iaculis eleifend eros vel dapibus. Phasellus lorem dolor, imperdiet non viverra ac, egestas eget arcu. Pellentesque finibus velit massa, in volutpat augue mattis et. Vivamus eu arcu elementum, ultricies ipsum vitae, interdum mi.

                Aenean dictum efficitur aliquet. Suspendisse pretium, purus non ultricies feugiat, ligula erat volutpat felis, eget consectetur justo nulla id odio. Donec nec blandit ex, dictum tincidunt quam. Suspendisse cursus imperdiet ipsum, at gravida lorem tincidunt et. Curabitur nec orci quis lacus tristique viverra. Phasellus et posuere felis. Nam nec dui erat. Sed efficitur pharetra rhoncus. Aenean finibus, leo sit amet ullamcorper faucibus, urna nisl feugiat purus, in volutpat lorem lacus quis sapien. Nulla elementum, diam a semper egestas, quam enim consequat nibh, nec pulvinar nunc justo at purus.

                Suspendisse commodo tortor venenatis enim volutpat semper. Vivamus fringilla rhoncus risus, bibendum pulvinar velit semper vitae. Donec malesuada massa accumsan leo eleifend, ullamcorper blandit lacus maximus. Pellentesque tempus ornare venenatis. Sed a fringilla eros, ac fringilla lectus. Suspendisse potenti. Nam tempus consequat viverra. Morbi feugiat lobortis turpis, nec vestibulum lectus tristique nec. Donec ornare enim gravida, gravida ante non, aliquam nulla. Aliquam risus augue, facilisis vitae elit mattis, semper aliquet enim. In facilisis lacinia arcu, et tincidunt elit tempor ut. Etiam euismod gravida vehicula. Proin a urna venenatis, viverra augue a, accumsan eros. Nulla in arcu lorem. Sed sit amet dignissim nibh, nec iaculis massa. Donec eleifend iaculis tortor et sagittis.

                Proin varius nunc vel ligula luctus, ut scelerisque lacus dapibus. Nulla vestibulum a neque blandit ultricies. Praesent sodales fringilla fringilla. Donec ac justo eget erat semper laoreet. Nulla libero massa, luctus at ornare eget, fermentum eu mauris. Sed laoreet volutpat nibh non pretium. Vestibulum pretium, massa a aliquam viverra, purus metus blandit elit, et porttitor velit augue in lorem. Pellentesque vel condimentum lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse accumsan mauris quis sem dignissim sagittis. Fusce lacinia iaculis nisl sed mattis.

                Aliquam accumsan felis elementum mi pharetra, nec dignissim magna euismod. Nam tincidunt risus sed pulvinar porta. Nunc quis nisi eget dolor lobortis viverra. Integer mollis sed neque vitae commodo. Etiam rhoncus, arcu et scelerisque aliquam, erat arcu consequat magna, iaculis semper lacus nunc ut diam. In luctus vulputate consectetur. Sed vehicula lorem vel sodales condimentum. Integer risus nisi, sollicitudin vel sem sit amet, volutpat venenatis elit.

                Fusce hendrerit finibus tellus, quis lobortis diam congue facilisis. Morbi at dui nec sapien sollicitudin iaculis. Aliquam bibendum ante magna, at consequat metus mollis eu. Fusce dignissim, tellus scelerisque condimentum viverra, dolor lectus elementum enim, vitae bibendum eros felis id massa. Maecenas in efficitur tellus. In id nulla tincidunt, aliquet velit eget, gravida ante. Integer eu libero vel est facilisis maximus sit amet sit amet turpis. Nam iaculis commodo fringilla. Vestibulum facilisis quis velit sed dapibus. Suspendisse in orci tincidunt, blandit purus ut, euismod lacus. Aenean vehicula odio porta, auctor velit at, dignissim ipsum. Mauris quis pharetra tortor. Vivamus accumsan consectetur odio vel ultrices. Phasellus nec euismod justo. Donec id leo dui.

                Curabitur vitae odio hendrerit, dictum velit sit amet, facilisis quam. Ut aliquam felis semper lectus ullamcorper posuere. Pellentesque ut nibh eu odio sodales aliquam vitae eu lectus. Praesent risus purus, mattis ac condimentum eget, ultricies ut neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam vestibulum tortor non urna blandit, non porta leo rhoncus. Sed fringilla massa at justo rhoncus congue. Quisque congue egestas urna, lacinia lobortis metus tempor id.
                </p>
        </div>
    );
}

export default Home;